from sqlalchemy.orm import Session
from .models import Profile, Task

TASKS = [
    dict(skill="Python", title="Student Data Cleaner", difficulty="Intermediate", estimated_minutes=35,
         description="Clean a messy student dataset and identify data-quality issues.",
         scenario="A college office received a student CSV containing duplicates and missing attendance values. Clean it and explain your decisions.",
         requirements=["Inspect the dataset before changing it", "Remove duplicate records", "Handle missing attendance values", "Explain at least one cleaning decision"],
         resource="students_messy.csv",
         starter_code='import pandas as pd\n\n# Load the dataset\ndf = pd.read_csv("students_messy.csv")\n\n# Inspect the data first\nprint(df.head())\nprint(df.isna().sum())\n\n# Your cleaning steps below:\n',
         evaluation_criteria={"Correctness":"Strong", "Approach":"Good", "Problem Solving":"Strong", "Understanding":"Needs Improvement"}),
    dict(skill="Power BI", title="Sales Insight Dashboard", difficulty="Intermediate", estimated_minutes=50,
         description="Analyse sales data and create a dashboard for a business manager.",
         scenario="A retail manager needs a compact view of revenue, profit and category performance.",
         requirements=["Identify key KPIs", "Find at least two useful trends", "Explain one unusual pattern", "Design a decision-ready dashboard"],
         resource="sales_2026.csv", starter_code="# Power BI task\n# Document your data preparation and dashboard decisions here.\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Good","Problem Solving":"Strong","Understanding":"Good"}),
    dict(skill="Excel", title="Budget Investigation", difficulty="Beginner", estimated_minutes=30,
         description="Analyse six months of spending and identify useful cost-saving insights.",
         scenario="A student club wants to understand where its monthly budget is going.",
         requirements=["Clean the table", "Calculate category totals", "Identify the largest cost driver", "Give two evidence-based recommendations"],
         resource="club_budget.xlsx", starter_code="# Excel task\n# Record your formulas and investigation notes here.\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Good","Problem Solving":"Good","Understanding":"Good"}),
    dict(skill="Data Analysis", title="Customer Churn Clues", difficulty="Intermediate", estimated_minutes=45,
         description="Analyse customer data and identify important churn patterns.",
         scenario="A subscription business wants to understand which customer behaviours are associated with churn.",
         requirements=["Inspect churn rate", "Compare at least two customer groups", "Identify a meaningful pattern", "Separate observation from assumption"],
         resource="customers.csv", starter_code="# Data analysis task\n# Write your investigation plan and findings here.\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Strong","Problem Solving":"Strong","Understanding":"Good"}),
    dict(skill="Canva", title="Campaign Creative Brief", difficulty="Beginner", estimated_minutes=25,
         description="Turn a product brief into a clear social campaign concept.",
         scenario="A student startup needs a simple campaign concept that can be translated into three social posts.",
         requirements=["Define the audience", "Create a visual direction", "Write three concise content ideas", "Explain the design choices"],
         resource="campaign_brief.pdf", starter_code="# Canva task\n# Write your creative concept, audience and design reasoning here.\n",
         evaluation_criteria={"Correctness":"Good","Approach":"Strong","Problem Solving":"Good","Understanding":"Strong"}),
    dict(skill="SQL", title="Order Investigation", difficulty="Intermediate", estimated_minutes=40,
         description="Query transaction data to find anomalies and explain the findings.",
         scenario="An operations team suspects a small number of unusual orders are affecting weekly reporting.",
         requirements=["Inspect the schema", "Write a query to find suspicious records", "Group results meaningfully", "Explain what the query proves and does not prove"],
         resource="orders.db", starter_code="-- SQL task\n-- Start by inspecting the available tables.\n\nSELECT * FROM orders LIMIT 10;\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Strong","Problem Solving":"Strong","Understanding":"Good"}),
    dict(skill="Python", title="Expense Tracker Analyzer", difficulty="Beginner", estimated_minutes=30,
         description="Turn a personal expense CSV into useful monthly insights.",
         scenario="You have six months of expense transactions and need to understand spending patterns.",
         requirements=["Parse dates", "Calculate monthly totals", "Group by category", "State one limitation of your analysis"],
         resource="expenses.csv", starter_code='import pandas as pd\n\ndf = pd.read_csv("expenses.csv")\nprint(df.head())\n\n# Continue the analysis here.\n',
         evaluation_criteria={"Correctness":"Good","Approach":"Good","Problem Solving":"Good","Understanding":"Good"}),
    dict(skill="Python", title="Inventory Quality Check", difficulty="Advanced", estimated_minutes=55,
         description="Investigate product inventory records and surface data-quality risks.",
         scenario="A warehouse export contains inconsistent product identifiers and suspicious quantities.",
         requirements=["Profile the data", "Find inconsistencies", "Choose a validation strategy", "Explain trade-offs"],
         resource="inventory.csv", starter_code="# Start your investigation here.\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Strong","Problem Solving":"Strong","Understanding":"Strong"}),
    dict(skill="Power BI", title="HR Analytics Dashboard", difficulty="Intermediate", estimated_minutes=50,
         description="Build a compact HR dashboard from employee data.",
         scenario="HR wants to monitor headcount, department mix and attrition patterns.",
         requirements=["Choose useful KPIs", "Create at least two breakdowns", "Identify one pattern", "Explain one misleading interpretation to avoid"],
         resource="employees.csv", starter_code="# Power BI work notes\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Good","Problem Solving":"Strong","Understanding":"Strong"}),
    dict(skill="Excel", title="Loan Payment Investigation", difficulty="Intermediate", estimated_minutes=40,
         description="Use formulas and scenario analysis to understand loan payments.",
         scenario="Compare payment outcomes across different rates and durations.",
         requirements=["Build the calculation", "Use cell references", "Compare scenarios", "Explain the main driver"],
         resource="loan_scenarios.xlsx", starter_code="# Excel work notes\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Good","Problem Solving":"Strong","Understanding":"Good"}),
    dict(skill="Data Analysis", title="Marketing Campaign Analysis", difficulty="Intermediate", estimated_minutes=45,
         description="Evaluate campaign performance and identify what needs investigation.",
         scenario="A marketing team has campaign-level spend, clicks and conversions.",
         requirements=["Calculate useful rates", "Compare campaigns", "Flag a misleading metric", "Make a testable next-step hypothesis"],
         resource="campaigns.csv", starter_code="# Analysis notes\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Strong","Problem Solving":"Strong","Understanding":"Strong"}),
    dict(skill="SQL", title="Customer Retention Query", difficulty="Advanced", estimated_minutes=55,
         description="Use SQL to investigate repeat purchasing behaviour.",
         scenario="A store wants to identify customers who returned after their first purchase.",
         requirements=["Understand the order dates", "Identify first purchases", "Find repeat behaviour", "Explain edge cases"],
         resource="retention.db", starter_code="-- Start by exploring the schema.\n",
         evaluation_criteria={"Correctness":"Strong","Approach":"Strong","Problem Solving":"Strong","Understanding":"Strong"}),
]

def seed(db: Session):
    if db.query(Profile).count() == 0:
        db.add(Profile(name="Abdul Baseeth", degree="B.Sc Data Science", college="Student", email="student@example.com",
                       about="Data science student building practical, evidence-based skills."))
    if db.query(Task).count() == 0:
        db.add_all([Task(**t) for t in TASKS])
    db.commit()
